### ISSUE TITLE
✨ FEATURE: Projects Page Feed

### ISSUE THREAD

**Issue by PuranjotSinghNaga** [Robotics-Society-PEC/Robotics-Society-PEC.github.io#12]
Have to make a projects page feed which will show the latest uploaded projects in the projects db 

### Tasks to do 
- [ ] Make a Project Feed
- [ ] Add Pages to the Project Feed 
- [ ] Add Sorting for most rated projects, trending projects and latest projects
- [ ] Add a search functionality to search through the projects list 
- [ ] Use Tags to filter out Projects according to the most famous tags
