### ISSUE TITLE
✨ FEATURE: Project Notion Like Editor 

### ISSUE THREAD

**Issue by PuranjotSinghNaga** [Robotics-Society-PEC/Robotics-Society-PEC.github.io#13]
Make a Notion like editor which can be used to write custom data about a project including headings and images and is intuitive enough for beginner users 

### Task List 

- [ ] Make a notion/Medium like project editor 
- [ ] Add the ability to add custom tags or currently popular tags 
- [ ] add the ability to include code blocks and youtube embedds 
- [ ] add the ability to add helping members 
- [ ] add the ability to make a group project rather than a single person project
